# Generated by Django 5.1.4 on 2024-12-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Gaming', 'Gaming'), ('Cloth', 'Cloth'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Toys', 'Toys'), ('Books', 'Books'), ('Beauty', 'Beauty'), ('Sports', 'Sports'), ('Automotive', 'Automotive'), ('Jewelry', 'Jewelry'), ('Home Appliances', 'Home Appliances'), ('Music', 'Music'), ('Pet Supplies', 'Pet Supplies'), ('Groceries', 'Groceries'), ('Health', 'Health'), ('Garden', 'Garden'), ('Office Supplies', 'Office Supplies'), ('Footwear', 'Footwear'), ('Baby Products', 'Baby Products'), ('Travel', 'Travel')], default=None, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_ordered', models.BooleanField(default=False)),
            ],
        ),
    ]
