# Generated by Django 5.1.4 on 2024-12-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Gaming', 'Gaming'), ('Cloth', 'Cloth'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Toys', 'Toys'), ('Books', 'Books'), ('Beauty', 'Beauty'), ('Sports', 'Sports'), ('Automotive', 'Automotive'), ('Jewelry', 'Jewelry'), ('Home Appliances', 'Home Appliances'), ('Music', 'Music'), ('Pet Supplies', 'Pet Supplies'), ('Groceries', 'Groceries'), ('Health', 'Health'), ('Garden', 'Garden'), ('Office Supplies', 'Office Supplies'), ('Footwear', 'Footwear'), ('Baby Products', 'Baby Products'), ('Travel', 'Travel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
